//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ass_email_sender
    {
        public int id { get; set; }
        public string ent_cd { get; set; }
        public string email { get; set; }
        public string password { get; set; }
        public string email_template { get; set; }
    }
}
