//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ass_category
    {
        public ass_category()
        {
            this.childs = new HashSet<ass_category>();
            this.ass_complaint_dtl = new HashSet<ass_complaint_dtl>();
        }
    
        public int id { get; set; }
        public Nullable<int> parent_id { get; set; }
        public string name { get; set; }
        public string descs { get; set; }
        public Nullable<int> work_duration { get; set; }
        public System.DateTime audit_date { get; set; }
        public int user_id { get; set; }
        public bool is_main { get; set; }
    
        public virtual ICollection<ass_category> childs { get; set; }
        public virtual ass_category parent { get; set; }
        public virtual ICollection<ass_complaint_dtl> ass_complaint_dtl { get; set; }
        public virtual ass_user ass_user { get; set; }
    }
}
