//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ass_status
    {
        public ass_status()
        {
            this.ass_status_update = new HashSet<ass_status_update>();
            this.ass_complaint_dtl = new HashSet<ass_complaint_dtl>();
            this.status_flow_current = new HashSet<ass_status_flow>();
            this.status_flow_next = new HashSet<ass_status_flow>();
        }
    
        public int id { get; set; }
        public string name { get; set; }
        public string descs { get; set; }
    
        public virtual ICollection<ass_status_update> ass_status_update { get; set; }
        public virtual ICollection<ass_complaint_dtl> ass_complaint_dtl { get; set; }
        public virtual ICollection<ass_status_flow> status_flow_current { get; set; }
        public virtual ICollection<ass_status_flow> status_flow_next { get; set; }
    }
}
