//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ass_migrate_lastmonth
    {
        public ass_migrate_lastmonth()
        {
            this.ass_migrate_closing = new HashSet<ass_migrate_closing>();
        }
    
        public int id { get; set; }
        public string ent_cd { get; set; }
        public string project_no { get; set; }
        public int on_progress { get; set; }
        public int closing { get; set; }
        public System.DateTime cutoff_date { get; set; }
    
        public virtual ICollection<ass_migrate_closing> ass_migrate_closing { get; set; }
        public virtual pl_project pl_project { get; set; }
    }
}
