//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ass_complaint
    {
        public ass_complaint()
        {
            this.ass_complaint_dtl = new HashSet<ass_complaint_dtl>();
            this.ass_complaint_mail = new HashSet<ass_complaint_mail>();
        }
    
        public int id { get; set; }
        public string complaint_cd { get; set; }
        public string entity_cd { get; set; }
        public string project_no { get; set; }
        public string lot_no { get; set; }
        public string business_id { get; set; }
        public string cp_name { get; set; }
        public string cp_telp { get; set; }
        public System.DateTime check_date { get; set; }
        public int contractor_id { get; set; }
        public string descs { get; set; }
        public System.DateTime input_date { get; set; }
        public int user_id { get; set; }
        public byte[] attach_file { get; set; }
        public string cp_email { get; set; }
        public Nullable<System.DateTime> closing_date { get; set; }
        public string controller_name { get; set; }
        public Nullable<System.DateTime> cancel_date { get; set; }
        public int priority_id { get; set; }
    
        public virtual ICollection<ass_complaint_dtl> ass_complaint_dtl { get; set; }
        public virtual cm_contractor cm_contractor { get; set; }
        public virtual ass_user ass_user { get; set; }
        public virtual pm_tenancy pm_tenancy { get; set; }
        public virtual ICollection<ass_complaint_mail> ass_complaint_mail { get; set; }
        public virtual ass_priority ass_priority { get; set; }
    }
}
