//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ass_migrate_closing
    {
        public int id { get; set; }
        public int migrate_id { get; set; }
        public int closing { get; set; }
        public System.DateTime closing_date { get; set; }
        public int user_id { get; set; }
        public System.DateTime audit_date { get; set; }
    
        public virtual ass_migrate_lastmonth ass_migrate_lastmonth { get; set; }
        public virtual ass_user ass_user { get; set; }
    }
}
