//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ass_status_update
    {
        public int id { get; set; }
        public int compdtl_id { get; set; }
        public int status_id { get; set; }
        public System.DateTime status_date { get; set; }
        public string remark { get; set; }
        public int user_id { get; set; }
    
        public virtual ass_complaint_dtl ass_complaint_dtl { get; set; }
        public virtual ass_status ass_status { get; set; }
        public virtual ass_user ass_user { get; set; }
    }
}
