//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class ass_user
    {
        public ass_user()
        {
            this.ass_category = new HashSet<ass_category>();
            this.ass_complaint = new HashSet<ass_complaint>();
            this.ass_location = new HashSet<ass_location>();
            this.ass_status_update = new HashSet<ass_status_update>();
            this.cm_contractor = new HashSet<cm_contractor>();
            this.pm_lot_contractor = new HashSet<pm_lot_contractor>();
            this.ass_user1 = new HashSet<ass_user>();
            this.ass_reminder = new HashSet<ass_reminder>();
            this.ass_reminder1 = new HashSet<ass_reminder>();
            this.ass_complaint_mail = new HashSet<ass_complaint_mail>();
            this.ass_migrate_closing = new HashSet<ass_migrate_closing>();
            this.ass_priority = new HashSet<ass_priority>();
        }
    
        public int id { get; set; }
        public string username { get; set; }
        public string fullname { get; set; }
        public string password { get; set; }
        public Nullable<System.DateTime> audit_date { get; set; }
        public Nullable<int> user_id { get; set; }
    
        public virtual ICollection<ass_category> ass_category { get; set; }
        public virtual ICollection<ass_complaint> ass_complaint { get; set; }
        public virtual ICollection<ass_location> ass_location { get; set; }
        public virtual ICollection<ass_status_update> ass_status_update { get; set; }
        public virtual ICollection<cm_contractor> cm_contractor { get; set; }
        public virtual ICollection<pm_lot_contractor> pm_lot_contractor { get; set; }
        public virtual ICollection<ass_user> ass_user1 { get; set; }
        public virtual ass_user ass_user2 { get; set; }
        public virtual ICollection<ass_reminder> ass_reminder { get; set; }
        public virtual ICollection<ass_reminder> ass_reminder1 { get; set; }
        public virtual ICollection<ass_complaint_mail> ass_complaint_mail { get; set; }
        public virtual ICollection<ass_migrate_closing> ass_migrate_closing { get; set; }
        public virtual ICollection<ass_priority> ass_priority { get; set; }
    }
}
