//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cf_business
    {
        public cf_business()
        {
            this.pm_tenancy = new HashSet<pm_tenancy>();
        }
    
        public string business_id { get; set; }
        public string class_cd { get; set; }
        public string category { get; set; }
        public string name { get; set; }
        public string salutation { get; set; }
        public string address1 { get; set; }
        public string address2 { get; set; }
        public string address3 { get; set; }
        public string post_cd { get; set; }
        public string tel_no { get; set; }
        public string hand_phone { get; set; }
        public string fax_no { get; set; }
        public string sex { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public string nationality { get; set; }
        public string marital_status { get; set; }
        public string income_tax { get; set; }
        public string mail_type { get; set; }
        public string mail_addr1 { get; set; }
        public string mail_addr2 { get; set; }
        public string mail_addr3 { get; set; }
        public string mail_post_cd { get; set; }
        public string co_name { get; set; }
        public string co_addr1 { get; set; }
        public string co_addr2 { get; set; }
        public string co_addr3 { get; set; }
        public string co_post_cd { get; set; }
        public string co_tel_no { get; set; }
        public string co_fax_no { get; set; }
        public string designation { get; set; }
        public string contact_person { get; set; }
        public string statement_type { get; set; }
        public string interest { get; set; }
        public string reminder { get; set; }
        public string credit_terms { get; set; }
        public string remark { get; set; }
        public string audit_user { get; set; }
        public System.DateTime audit_date { get; set; }
        public string religion_cd { get; set; }
    
        public virtual ICollection<pm_tenancy> pm_tenancy { get; set; }
    }
}
