//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cm_contractor
    {
        public cm_contractor()
        {
            this.ass_complaint = new HashSet<ass_complaint>();
            this.pm_lot_contractor = new HashSet<pm_lot_contractor>();
        }
    
        public int id { get; set; }
        public string creditor_acct { get; set; }
        public string trade { get; set; }
        public string address { get; set; }
        public string telp { get; set; }
        public string cp_name { get; set; }
        public int user_id { get; set; }
        public System.DateTime audit_date { get; set; }
    
        public virtual ICollection<ass_complaint> ass_complaint { get; set; }
        public virtual ICollection<pm_lot_contractor> pm_lot_contractor { get; set; }
        public virtual ass_user ass_user { get; set; }
    }
}
