//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASS.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class pm_lot_contractor
    {
        public int id { get; set; }
        public string ent_cd { get; set; }
        public string project_no { get; set; }
        public string lot_no { get; set; }
        public int contractor_id { get; set; }
        public int user_id { get; set; }
        public System.DateTime audit_date { get; set; }
    
        public virtual cm_contractor cm_contractor { get; set; }
        public virtual ass_user ass_user { get; set; }
    }
}
