//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASS.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class POM_DasanaEntities : DbContext
    {
        public POM_DasanaEntities()
            : base("name=POM_DasanaEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ass_category> ass_category { get; set; }
        public virtual DbSet<ass_complaint> ass_complaint { get; set; }
        public virtual DbSet<ass_complaint_dtl> ass_complaint_dtl { get; set; }
        public virtual DbSet<ass_location> ass_location { get; set; }
        public virtual DbSet<ass_status> ass_status { get; set; }
        public virtual DbSet<ass_status_update> ass_status_update { get; set; }
        public virtual DbSet<ass_status_flow> ass_status_flow { get; set; }
        public virtual DbSet<ass_reminder> ass_reminder { get; set; }
        public virtual DbSet<cm_contractor> cm_contractor { get; set; }
        public virtual DbSet<pm_lot_contractor> pm_lot_contractor { get; set; }
        public virtual DbSet<ass_user> ass_user { get; set; }
        public virtual DbSet<cf_business> cf_business { get; set; }
        public virtual DbSet<pl_project> pl_project { get; set; }
        public virtual DbSet<pm_lot> pm_lot { get; set; }
        public virtual DbSet<pm_tenancy> pm_tenancy { get; set; }
        public virtual DbSet<ass_complaint_mail> ass_complaint_mail { get; set; }
        public virtual DbSet<ass_migrate_closing> ass_migrate_closing { get; set; }
        public virtual DbSet<ass_migrate_lastmonth> ass_migrate_lastmonth { get; set; }
        public virtual DbSet<ass_email_sender> ass_email_sender { get; set; }
        public virtual DbSet<ass_priority> ass_priority { get; set; }
    }
}
